# Dependencies
highlighter:      pygments
markdown:	  redcarpet

# Permalinks
permalink:        pretty

# Setup
title:            '我是铎铎'
tagline:          '寒山不系江心月 世间云外刹那灯'
description:      'My random translations. Tech and news in particular.'
url:              http://lingduo.net.cn

author:
  name:           'Lingduo'
  url:            http://weibo.com/u/5585285652

gems: [jekyll-paginate, jekyll-gist]
paginate:         10
gems:		  [jekyll-paginate]

# Custom vars
version:          0.0.9

github:
  repo:           https://github.com/duoduoeeee
