# Jekyll configuration

name: 我是铎铎
description: 寒山不系江心月 世间云外刹那灯

# url is currently only used only for the RSS feed in feed.xml
url: https://lingduo.net.cn

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: 'duoduoeeee'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: false

permalink: /:year/:title
paginate: 10

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']
