#markdown: rdiscount
highlighter: 'pygments'
#paginate: 10

title: "Lingduo's blog"
xyquote: ""
url: https://duoduoeeee.github.io
feed:
author_info: <a href="https://duoduoeeee.github.io/">Lingduo</a>

##notificationd##
alert: 
alright: 
warning: 
notification: